### ISSUE TITLE
Rename HashVer/hashVer to CommitVer/commitVer

### ISSUE THREAD

**Issue by BobWall23** [IronCoreLabs/davenport#26]
I think the name "hashVer" may lead users to think they are responsible for computing and submitting this value. (Actually, reading the documentation from couchbase, I'm not even sure it is actually a hash).

**Comment by coltfred** [comment]
Addressed in #30 - Will you please review and tell me if that's what you had in mind?

**Comment by coltfred** [comment]
This is closed by #30.
