### ISSUE TITLE
Rename interpreter

### ISSUE THREAD

**Issue by BobWall23** [IronCoreLabs/davenport#29]
The fact that davenport is implemented using Scala free monads seems like a detail that could be hidden. The name "interpreter" doesn't seem to help much with comprehending the package and how to use it.

**Comment by coltfred** [comment]
I'm not sure exactly what you're asking for. As a user of the library you eventually will have to "run" your `DBProg` through one of the interpreters (or one you've written yourself). Are you sad about the name interpreter or something else? 

The example in [storing and retreiving wrappers](https://github.com/IronCoreLabs/davenport/blob/master/src/tutsrc/storing-and-retrieving-wrappers.md) shows how an end user would use it and they certainly need to run it through an interpreter at some point.

If I'm missing your point entirely please post more details about what you're trying to do and how you'd expect it to work.

Thanks!

**Comment by BobWall23** [comment]
It’s the name that makes me sad. Doobie doesn’t have an “interpreter” or “interpret” anywhere, it has a “transact”. In the context of Doobie, that name makes sense.

**Comment by coltfred** [comment]
I didn't call it transactor because I make no guarantees about transactions inside of a DBProg. What would suggest for a name? I don't have a better one, but I'm certainly open to a different one.

**Comment by coltfred** [comment]
Quoting from Slack so that all the info is here:
@BobWall23 said
```
“datastore” instead of interpreter, maybe. “execute” or “run” or “apply” instead of “interpret”.
```

@zmre, What are your thoughts? I don't care either way I guess. 

Example usage:

```
val memDatastore = MemDatastore.empty
val program: DBProg[User] = ...
memDatastore.executer(program)
```

**Comment by zmre** [comment]
Works for me.  I think that's more intuitive although further away from similar functional libraries.  But I think as a tradeoff, I'd prefer intuitive anyway.  cc/ @coltfred @BobWall23
