### ISSUE TITLE
Bucket passwords should not be passed around in plain text

### ISSUE THREAD

**Issue by zmre** [IronCoreLabs/davenport#42]
I shudder when I see plain text passwords passed around and stored in config files or in source code.  It seems like we ought to be able to help a user out with that being as we are a crypto company and all.

The approach would be to create a separate tool or an API or both for someone to input a password and get back something encrypted.  Then when opening a bucket, maybe we have a plain text password option and maybe we have an encrypted password option.  We'll decrypt it, but meanwhile wherever it was stored was at least somewhat protected.

Our protection can't be fantastic, but I believe it would be better than nothing.  I would argue for generating a symmetric key using PBKDF1 using inputs that are specific to the calling application.  Or better yet, the app provides some identifier (preferably app name and some random number that they store) and that can be used to generate a key that unlocks the password.  So at least the app key is in code and the password is in the config file.  Pretty low level of security, but still better than plain text passwords floating around.

**Comment by BobWall23** [comment]
No need for encryption, I think. We take the bucket name, append a "password" from the config file, append an app key coded into the application, throw in some random salt, and hash. The salt plus the hash, base64 encoded, is the bucket password.

Not ideal, but you can't get into Couchbase directly using the password from the config file. You can change the password without rebuilding the app - just change the bucket password and update the config files.
App can maintain an app key and a "previous app key", so it can connect even if bucket password hasn't been updated with new release of app.

**Comment by BobWall23** [comment]
I guess salt doesn't make any sense, but I think a hash of the bucket name, the password from the config, and the app key should be about as good as it's going to get.

**Comment by zmre** [comment]
This can definitely be punted to the user of the library.  If we try to do something nice to help our library users manage their production passwords in intelligent ways, it way well be a separate project.  Or a recommendation to use a third party project.  This issue is low priority at best and possibly doesn't belong in this project.

**Comment by coltfred** [comment]
Closing.
