### ISSUE TITLE
Auto-turn on indexing (and note couchbase 4 dependency)

### ISSUE THREAD

**Issue by zmre** [IronCoreLabs/davenport#43]
Add `.queryEnabled(true)` to the environment builder.  That will require CouchBase 4, but as it is now officially released and we have other dependencies on it (key scanning) we should document that requirement anyway.

**Comment by coltfred** [comment]
@zmre We don't need to do this with couchbase 4.1. N1QL queries work fine without setting it. The [CoreEnvironment](https://github.com/couchbase/couchbase-jvm-core/blob/master/src%2Fmain%2Fjava%2Fcom%2Fcouchbase%2Fclient%2Fcore%2Fenv%2FCoreEnvironment.java#L113) has it deprecated saying it'll be autodetected.
